Create DS Code Documentation.md
krissemmy/HDSC-Spring-23-Premier-Project-plotly-group pull request #4
Opened 2023-06-14 18:01 UTC by armaf002

General outline and explanation of the code from the data science team

2023-06-14 20:45 UTC, armaf002 reviewed
This is not accurate, I will send new one

2023-06-14 21:54 UTC, krissemmy requested changes
can you change the notebook name to show it involve the data science aspect

2023-06-14 22:34 UTC, armaf002 commented
Alright

2023-06-15 10:43 UTC, krissemmy approved these changes

2023-06-15 10:43 UTC, merged